apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.60.1
    helm:
      releaseName: grafana
      values: |
        adminPassword: pussy 
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - panopticon.techfortress.com
        datasources: 
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: PrometheusMain
              type: prometheus
              url: http://192.168.0.65:30264
              access: proxy
              isDefault: false            
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: "Generated"
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default            
        dashboards:
          default:
            exporter:
              gnetId: 12486
              revision: 1
              datasource: PrometheusMain

