---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
spec:
  destination:
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.58.7
    chart: grafana
    helm:
      values: |
        admin:
          existingSecret: grafana
        ingress:
          enabled: true
          hosts: panopticon.techfortress.com          
        service:
          port: 3000
          type: LoadBalancer
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true