apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.60.1
    helm:
      releaseName: grafana
      values: |
        adminPassword: pussy 
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - panopticon.techfortress.com
        datasources: 
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus2
              type: prometheus
              url: http://prometheus-server.default.svc
              access: proxy
              isDefault: false