apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: kube-prometheus-stack-40.0.0
    path: charts/prometheus
    helm:
      values: |
        alertmanager:
          enabled: true
        kube-state-metrics:
          enabled: true  
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - prometheus.techfortress.com   
          service:
            type: LoadBalancer
        serverFiles:
          prometheus.yml:
            rule_files:
              - /etc/config/recording_rules.yml
              - /etc/config/alerting_rules.yml       
            scrape_configs:
              - job_name: prometheus  
                static_configs:
                  - targets:
                    - 192.168.0.29:9100
                    - 192.168.0.3:9100
                    - 192.168.0.21:9100   
                    - 192.168.0.44:9100  
                    - 192.168.0.44:9835
              - job_name: kube-state-metrics
                metrics_path: /metrics
                scheme: http
                static_configs:
                - targets:                    
                  - 10.102.8.10:8080
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=truehttps://www.vice.com/en/article/ozzy-osbourne-hates-christmas-drank-28-gallons-booze/
