apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        server:
          ingress:
            hosts: prometheus.techfortress.com
          service:
            type: LoadBalancer  
          ingress:
            enabled: true  
        pushgateway:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 15.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true




