apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: kube-prometheus-stack-40.0.0
    path: charts/prometheus
    helm:
      values: |
        alertmanager:
          enabled: true
        server:
          ingress:
            enabled: true
            hosts:
              - prometheus.techfortress.com   
            paths:
              - path: /
                pathType: ImplementationSpecific                      
          service:
            type: LoadBalancer
            port: 9000                
        serverFiles:
          prometheus.yml:
            rule_files:
              - /etc/config/recording_rules.yml
              - /etc/config/alerting_rules.yml       
            scrape_configs:
              - job_name: prometheus  
                static_configs:
                  - targets:
                    - 192.168.0.29:9100
                    - 192.168.0.3:9100
                    - 192.168.0.21:9100   
                    - 192.168.0.44:9100    
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true