argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    ingress:
      enabled: true
      hosts:
        - argocd.techfortress.com
    service:
      type: LoadBalancer
    extraArgs:
      - --insecure
